/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFtsoRegistry,
  IFtsoRegistryInterface,
} from "../../../contracts/FTSOReader.sol/IFtsoRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "symbol",
        type: "string",
      },
    ],
    name: "getCurrentPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "price",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IFtsoRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IFtsoRegistryInterface {
    return new Interface(_abi) as IFtsoRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IFtsoRegistry {
    return new Contract(address, _abi, runner) as unknown as IFtsoRegistry;
  }
}
