/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { FTSOReader__factory } from "./FTSOReader__factory";
export { IFtsoRegistry__factory } from "./IFtsoRegistry__factory";
